[project]
name = "sudoku"
version = "0.1.0"
requires-python = ">=3.14"

dependencies = [
    "PySide6>=6.10,<7",
]

[project.optional-dependencies]
dev = [
    "pytest",
    "ruff",
    "mypy",
    "python-dotenv",
]

[tool.pytest.ini_options]
testpaths = ["tests"]
pythonpath = ["src"]

[tool.ruff]
line-length = 100
target-version = "py314"

[tool.ruff.lint]
select = [
  "E",   # pycodestyle
  "F",   # pyflakes
  "I",   # import sorting
  "B",   # bugbear
  "UP",  # pyupgrade
]

[tool.ruff.format]
quote-style = 'single'
docstring-code-format = true

[tool.mypy]
python_version = "3.14"

strict = true
warn_unused_configs = true

pretty = true
show_error_codes = true
