from PySide6.QtWidgets import QGridLayout, QWidget

from domain.constants import GRID_SIZE
from engine.sudoku import Sudoku

from .cell import CellWidget


class BoardWidget(QWidget):
    def __init__(self, parent: QWidget | None = None):
        super().__init__(parent)

        self.sudoku: Sudoku | None = None

        self.setFixedSize(300, 300)

        grid = QGridLayout(self)
        grid.setSpacing(0)
        grid.setContentsMargins(0, 0, 0, 0)

        self.cells: list[list[CellWidget]] = []

        for row in range(GRID_SIZE):
            row_cells: list[CellWidget] = []
            for col in range(GRID_SIZE):
                cell = CellWidget(row, col, parent=self)
                cell.textChanged.connect(self._on_cell_changed)
                grid.addWidget(cell, row, col)
                row_cells.append(cell)
            self.cells.append(row_cells)

    def update_board(self, puzzle: Sudoku) -> None:
        """
        Used for populating the board with a starting puzzle
        generated by the Generator class.

        :param puzzle: An instance of the Sudoku class
        :type puzzle: Sudoku
        """
        self.sudoku = puzzle

        for row in range(GRID_SIZE):
            for col in range(GRID_SIZE):
                value = puzzle.grid[row][col].value
                cell = self.cells[row][col]

                if value != 0:
                    cell.setText(str(value))
                    cell.setReadOnly(True)
                else:
                    cell.clear()
                    cell.setReadOnly(False)

    def _on_cell_changed(self, text: str) -> None:
        """
        Used to call Sudoku.set_cell with the row, col, and val of the cell

        :param text: The input string value from CellWidget
        :type text: str
        """
        if self.sudoku is None:
            return

        cell: CellWidget = self.sender()  # type: ignore[assignment]
        value = int(text) if text else 0
        self.sudoku.set_cell(row=cell.row, col=cell.col, val=value)
        self._refresh_conflicts()

    def _refresh_conflicts(self) -> None:
        if self.sudoku is None:
            return

        for row in range(GRID_SIZE):
            for col in range(GRID_SIZE):
                engine_cell = self.sudoku.grid[row][col]
                ui_cell = self.cells[row][col]
                ui_cell.set_conflict(has_conflict=engine_cell.conflict_count > 0)
